// Configures Amplify once, at module load, from the generated outputs.
//
// amplify_outputs.json is produced by deploying the backend
// (`npm run sandbox` at the repo root) and is gitignored — it holds your real
// AppSync endpoint + API key. Until it exists, this import fails the bundle,
// which is why Amplify is only wired in when API_MODE === "amplify" (see
// client.ts). The require is isolated here so the rest of the app never
// touches Amplify config.
import { Amplify } from "aws-amplify";
// apps/tv/amplify_outputs.json is generated by the Amplify CLI. Produce it with
// either of (both write here via --out-dir / --outputs-out-dir):
//   npm run sandbox     # ampx sandbox --outputs-out-dir apps/tv
//   npm run outputs     # ampx generate outputs --out-dir apps/tv (deployed backend)
// It's gitignored (holds your real AppSync endpoint + API key).
import outputs from "../../amplify_outputs.json";

Amplify.configure(outputs);
